node {
	stage 'Checkout'
		checkout scm
	stage 'Build'
		bat 'C:\\Software\\nuget.exe restore GitGemo.sln'
		bat "\"${tool '.NET Build'}\" GitGemo.sln /p:VisualStudioVersion=14.0/p:Configuration=Release /p:Platform=\"Any CPU\" /p:ProductVersion=1.0.0.${env.BUILD_NUMBER}"

	stage 'Archive'
		bat 'Echo ToDo archive or working build'
	}